// routes/uploadRoutes.js
import express from 'express';
import { imageUpload } from '../middleware/uploadMiddleware.js';
import mediaController from '../controllers/mediaController.js';
import { authenticateToken, requireAdmin } from '../middleware/authMiddleware.js';
import { strictLimiter } from '../utils/limiters.js';
import { validateMediaUpload } from '../middleware/validationMiddleware.js';
import csrfProtection from '../utils/csrf.js';
import sharp from 'sharp';
import path from 'path';
import fs from 'fs/promises';
import { sanitizeFilename } from '../utils/utils.js';
import { getDatabasePool } from '../databases/mariaDB.js';


/**
 * Routes for media uploads.
 *
 * - `POST /image` accepts multipart/form-data with an `image` field and
 *   stores metadata in the media table. Only authenticated admins may
 *   create media entries.
 */
const uploadRouter = express.Router();

// Authenticate before multer: the file is buffered in memory (up to 25 MB),
// which must not be possible for anonymous clients.
uploadRouter.post('/image',
  strictLimiter,
  csrfProtection,
  authenticateToken,
  requireAdmin,
  imageUpload.single('image'),
  validateMediaUpload,
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({ 
          success: false, 
          error: 'No file uploaded', 
        });
      }
      const originalName = req.file.originalname;
      const safeOriginal = sanitizeFilename(originalName || 'upload');
      const now = new Date();
      const yyyy = String(now.getFullYear());
      const mm = String(now.getMonth() + 1).padStart(2, '0');

      // Persist under public/assets/media so it is served by express.static
      const publicRoot = path.join(process.cwd(), 'public');
      const mediaDir = path.join(publicRoot, 'assets', 'media', yyyy, mm);
      await fs.mkdir(mediaDir, { recursive: true });

      // Media-Objekt für Datenbank erstellen (postId optional)
      const parsedPostId = req.body && req.body.postId ? Number(req.body.postId) : null;
      const postId = Number.isFinite(parsedPostId) && parsedPostId > 0 ? parsedPostId : null;

      // Resolve a human-readable filename prefix from the post slug (if postId available)
      let prefix = null;
      if (postId) {
        try {
          let conn;
          try {
            conn = await getDatabasePool().getConnection();
            const rows = await conn.query('SELECT slug FROM posts WHERE id = ? LIMIT 1', [postId]);
            if (rows && rows.length > 0 && rows[0].slug) {
              prefix = rows[0].slug;
            }
          } finally {
            if (conn) conn.release();
          }
        } catch (_e) { /* fall back to original name */ }
      }
      if (!prefix) {
        prefix = (safeOriginal.replace(path.extname(safeOriginal), '') || 'image');
      }

      // Sequential counter: count existing files in this month's dir with the same prefix
      let n = 1;
      try {
        const existing = await fs.readdir(mediaDir);
        const pattern = new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}-\\d+\\.webp$`);
        n = existing.filter(f => pattern.test(f)).length + 1;
      } catch (_e) { /* directory may not exist yet, n stays 1 */ }

      const outFile = `${prefix}-${n}.webp`;
      const outPath = path.join(mediaDir, outFile);

      // Server-side optimization for LCP: rotate via EXIF, resize, encode to WebP
      const maxWidth = 1600;
      const webpQuality = 80;

      const transformer = sharp(req.file.buffer, { failOn: 'none' })
        .rotate()
        .resize({ width: maxWidth, withoutEnlargement: true })
        .webp({ quality: webpQuality });

      const metadata = await transformer.metadata();
      await transformer.toFile(outPath);

      const publicUrl = `/assets/media/${yyyy}/${mm}/${encodeURIComponent(outFile)}`;

      const rawAlt = req.body && typeof req.body.alt_text !== 'undefined' ? String(req.body.alt_text) : '';
      const altText = rawAlt.trim() !== '' ? rawAlt.trim() : undefined;

      const mediaData = {
        postId,
        original_name: originalName,
        file_size: req.file.size,
        mime_type: 'image/webp',
        uploaded_by: req.user.username,
        upload_path: publicUrl,
        ...(altText && { alt_text: altText }),
        // NOTE: width/height not stored in DB schema currently; keep in response only.
        // created_at is auto-generated by DB
      };

      const result = await mediaController.addMedia(mediaData);

      return res.json({
        success: true,
        message: 'Image uploaded successfully',
        location: publicUrl, // TinyMCE expects `location`
        url: publicUrl,
        media: {
          id: result.id,
          originalName,
          upload_path: publicUrl,
          mimeType: 'image/webp',
          width: metadata && metadata.width ? Number(metadata.width) : null,
          height: metadata && metadata.height ? Number(metadata.height) : null,
        },
      });
    } catch (error) {
      console.error('Upload error:', error);
      res.status(500).json({ 
        success: false, 
        error: error.message || 'Upload failed', 
      });
    }
  });

export default uploadRouter;