import { DatabaseService } from '../databases/mariaDB.js';
import { Card } from '../models/cardModel.js';
import { CardControllerException } from '../models/customExceptions.js';

/**
 * Erstellt eine neue Karte (Card) nach Validierung der Eingabedaten.
 *
 * @param {Object} cardData - Rohdaten für die Karte (title, description, img_link, etc.).
 * @returns {Promise<Card>} Die erstellte und validierte `Card`-Instanz.
 * @throws {CardControllerException} Wenn die Validierung oder DB-Operation fehlschlägt.
 */
const createCard = async (cardData) => {
  const { error, value } = Card.validate(cardData);
  if (error) {
    throw new CardControllerException('Validation failed: ' + error.details.map(d => d.message).join('; '));
  }
  try {
    const result = await DatabaseService.createCard(value);
    // DatabaseService.createCard returns { success: true, card: {...} }
    const created = result && result.card ? result.card : result;
    return new Card(created);
  } catch (error) {
    throw new CardControllerException(`Error creating card: ${error.message}`, error);
  }
};
/**
 * Legt einen automatisch erzeugten Entwurf an (wöchentlicher Card-Digest). Die Card ist immer
 * unveröffentlicht und als automatisch erzeugt markiert, damit sie nach Ablauf der
 * Aufbewahrungszeit wieder gelöscht werden kann (siehe getExpiredAutoCards).
 *
 * @param {Object} cardData - title, subtitle, link, img_link.
 * @returns {Promise<Card>} Die erstellte `Card`-Instanz.
 * @throws {CardControllerException} Wenn die Validierung oder DB-Operation fehlschlägt.
 */
const createAutoGeneratedCard = async (cardData) => {
  const { error, value } = Card.validate({ ...cardData, published: false });
  if (error) {
    throw new CardControllerException('Validation failed: ' + error.details.map(d => d.message).join('; '));
  }
  try {
    const result = await DatabaseService.createCard({ ...value, published: false, auto_generated: true });
    return new Card(result && result.card ? result.card : result);
  } catch (error) {
    throw new CardControllerException(`Error creating auto-generated card: ${error.message}`, error);
  }
};

/**
 * Unveröffentlichte, automatisch erzeugte Cards, die älter als `days` Tage sind.
 *
 * @param {number} days - Aufbewahrungszeit in Tagen (>= 1).
 * @returns {Promise<Array<{id: number, title: string, img_link: string}>>}
 * @throws {CardControllerException} Bei DB-Fehlern.
 */
const getExpiredAutoCards = async (days) => {
  try {
    return await DatabaseService.getExpiredAutoCards(days);
  } catch (error) {
    throw new CardControllerException(`Error getting expired auto-generated cards: ${error.message}`, error);
  }
};

/**
 * Löscht einen abgelaufenen automatisch erzeugten Entwurf. Eine Card, die inzwischen veröffentlicht
 * wurde, bleibt erhalten.
 *
 * @param {number} id
 * @returns {Promise<boolean>} True, wenn die Card gelöscht wurde.
 * @throws {CardControllerException} Bei DB-Fehlern.
 */
const deleteExpiredAutoCard = async (id) => {
  try {
    return await DatabaseService.deleteExpiredAutoCard(id);
  } catch (error) {
    throw new CardControllerException(`Error deleting expired auto-generated card: ${error.message}`, error);
  }
};
/**
 * Liest alle Karten aus der Datenbank, validiert jede Karte und gibt
 * ein Array von `Card`-Instanzen zurück. Ungültige Einträge werden übersprungen.
 *
 * @returns {Promise<Card[]>} Array gültiger `Card`-Instanzen (leer wenn keine Karten).
 * @throws {CardControllerException} Bei internen Fehlern beim Lesen aus der DB.
 */
const getAllCards = async () => {
  try {
    const cards = await DatabaseService.getAllCards();
    if (!cards || cards.length === 0) {
      return [];
    }
    // validate
    const validCards = [];
    for (const card of cards) {
      const { error, value } = Card.validate(card);
      if (error) {
        console.error('Validation failed for card:', error.details.map(d => d.message).join('; '));
        continue;
      }
      validCards.push(new Card(value));
    }
    return validCards;
  } catch (error) {
    throw new CardControllerException(`Error getting all cards: ${error.message}`, error);
  }
};
/**
 * Holt eine Karte anhand ihrer numerischen ID, validiert sie und gibt
 * die `Card`-Instanz zurück.
 *
 * @param {number} id - Numerische ID der Karte (größer als 0).
 * @returns {Promise<Card>} Validierte `Card`-Instanz.
 * @throws {CardControllerException} Bei ungültiger ID, nicht gefunden oder Validierungsfehler.
 */
const getCardById = async (id) => {
  try {
    if (!Number.isInteger(id) || id <= 0) {
      throw new CardControllerException('Invalid card ID');
    }
    const card = await DatabaseService.getCardById(id);
    if (!card) {
      throw new CardControllerException('Card not found');
    }
    const { error, value } = Card.validate(card);
    if (error) {
      throw new CardControllerException('Validation failed: ' + error.details.map(d => d.message).join('; '));
    }
    return new Card(value);
  } catch (error) {
    throw new CardControllerException(`Error getting card by id: ${error.message}`, error);
  }
};
/**
 * Löscht eine Karte anhand ihrer ID.
 *
 * @param {number} id - Numerische ID der Karte.
 * @returns {Promise<Object>} Ergebnisobjekt mit Erfolgsmeldung.
 * @throws {CardControllerException} Bei ungültiger ID oder wenn das Löschen fehlschlägt.
 */
const updateCard = async (id, cardData) => {
  if (!Number.isInteger(id) || id <= 0) {
    throw new CardControllerException('Invalid card ID');
  }
  const { error, value } = Card.validate({ ...cardData, id });
  if (error) {
    throw new CardControllerException('Validation failed: ' + error.details.map(d => d.message).join('; '));
  }
  try {
    await DatabaseService.updateCard(id, value);
    return new Card({ ...value, id });
  } catch (err) {
    throw new CardControllerException(`Error updating card: ${err.message}`, err);
  }
};

const deleteCard = async (id) => {
  try {
    if (!Number.isInteger(id) || id <= 0) {
      throw new CardControllerException('Invalid card ID');
    }
    const deleted = await DatabaseService.deleteCard(id);
    if (!deleted) {
      throw new CardControllerException('Card not found or not deleted');
    }
    return { success: true, message: 'Card deleted successfully' };
  } catch (error) {
    throw new CardControllerException(`Error deleting card: ${error.message}`, error);
  }
};
export const CARDS_PER_PAGE = 9;

const getAllCardsAdmin = async () => {
  try {
    const cards = await DatabaseService.getAllCardsAdmin();
    const validCards = [];
    for (const card of (cards || [])) {
      const { error, value } = Card.validate(card);
      if (error) {
        console.error('Validation failed for card:', error.details.map(d => d.message).join('; '));
        continue;
      }
      validCards.push(new Card(value));
    }
    return validCards;
  } catch (error) {
    throw new CardControllerException(`Error getting all cards (admin): ${error.message}`, error);
  }
};

const getCardsPaginated = async (page) => {
  const offset = (page - 1) * CARDS_PER_PAGE;
  try {
    const [cards, total] = await Promise.all([
      DatabaseService.getCardsPaginated(CARDS_PER_PAGE, offset),
      DatabaseService.getPublishedCardsCount(),
    ]);
    const validCards = [];
    for (const card of (cards || [])) {
      const { error, value } = Card.validate(card);
      if (error) {
        console.error('Validation failed for card:', error.details.map(d => d.message).join('; '));
        continue;
      }
      validCards.push(new Card(value));
    }
    return { cards: validCards, total };
  } catch (error) {
    throw new CardControllerException(`Error getting paginated cards: ${error.message}`, error);
  }
};

export default {
  createCard,
  createAutoGeneratedCard,
  getExpiredAutoCards,
  deleteExpiredAutoCard,
  updateCard,
  getAllCards,
  getAllCardsAdmin,
  getCardsPaginated,
  getCardById,
  deleteCard,
};